version: '2'

networks:
  frontend:
  backend:

volumes:
  shopwaredemo_db: {}
  shopwaredemo_es: {}

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  php-7.0:
    image: pmphillip/shopware-php7
    container_name: cli
    volumes:
      - ./public:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=shopware
      - MYSQL_PASSWORD=shopware
    volumes:
      - shopwaredemo_db:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shopwaredemo_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      # Set the timezone
      TZ: "Europe/Berlin"
    expose:
      - 80
    ports:
      - 8083:80
    networks:
      - frontend
      - backend

  es:
    build: ES
    container_name: shopwaredemo_es_1
    command: "elasticsearch \
      -Des.cluster.name=shopwaredemo \
      -Des.discovery.zen.minimum_master_nodes=1 \
      -Des.discovery.zen.ping.unicast.hosts=es"
    volumes:
      - shopwaredemo_es:/usr/share/elasticsearch/data
    environment:
      # Set the timezone
      - "TZ=Europe/Berlin"
    networks:
      - frontend # For head plugin
      - backend
    ports:
      - 9200:9200
    expose:
      - 9200
