web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./public:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-7.0       
php-7.0:
    image: php
    volumes:
        - ./public:/var/www/html
    links:
        - mysql
mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=shopware
      - MYSQL_PASSWORD=shopware
